kind: pipeline
name: default

steps:
- name: docker-build
  image: plugins/docker
  settings:
    registry: 192.168.20.172
    repo: 192.168.20.172/kyle/meowmeow-manager
    dockerfile: Dockerfile
    username: admin
    password: 
      from_secret: docker_password
    insecure: true
    tags: ${DRONE_COMMIT_SHA:0:8} 
